<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pomodoro Zamanlayıcı</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-color: #f4f4f4;
        }
        #timer {
            font-size: 3em;
            color: #ff6347;
        }
        button {
            margin-top: 20px;
            padding: 10px 20px;
            font-size: 1em;
            background-color: #ff6347;
            color: white;
            border: none;
            cursor: pointer;
            border-radius: 5px;
        }
        button:hover {
            background-color: #e5533e;
        }
    </style>
</head>
<body>
    <div>
        <div id="timer">25:00</div>
        <button onclick="startPomodoro()">Başlat</button>
    </div>
    <script>
        let timer;
        function startPomodoro() {
            let minutes = 25;
            let seconds = 0;
            timer = setInterval(() => {
                if (seconds === 0) {
                    if (minutes === 0) {
                        clearInterval(timer);
                        alert("Pomodoro tamamlandı!");
                        return;
                    }
                    minutes--;
                    seconds = 59;
                } else {
                    seconds--;
                }
                document.getElementById("timer").innerText =
                    `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
            }, 1000);
        }
    </script>
</body>
</html>
